#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    #colorscheme = "one"
    colorscheme = "tokyonight"
    #colorscheme = "iceberg"
    #colorscheme_bg = "dark"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "JetBrains_Mono_NL:h14"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "checkers"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
    name = "lang#c"

[[layers]]
    name = "lang#java"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#r"

[[custom_plugins]]
    repo = 'neoclide/coc.nvim'
    merged = false

[[custom_plugins]]
    repo = 'nvim-treesitter/nvim-treesitter'
    merged = false

[[custom_plugins]]
    repo = 'folke/tokyonight.nvim'
    merged = false

[[custom_plugins]]
    repo = 'cocopon/iceberg.vim'
    merged = false

[[custom_plugins]]
    repo = 'alec-gibson/nvim-tetris'
    merged = false

